// Class automatically generated by Dev-C++ New Class wizard

#ifndef PUNTO3D_H
#define PUNTO3D_H

#include "punto.h" // inheriting class's header file

// No description
class Punto3D : public Punto
{
	protected:
        float z;
        
    public:
		// class constructor
		Punto3D();
		Punto3D(float i);
		Punto3D(float i, float j, float k);
		// class destructor
		~Punto3D();
};

#endif // PUNTO3D_H
