// Class automatically generated by Dev-C++ New Class wizard

#include "punto.h" // class's header file
#include <cstdlib>
#include <iostream>

using namespace std;

// class constructor
Punto::Punto()
{
    x=0;
    y=0;
}
Punto::Punto(float i)
{
    i=x;
    x=y;
}
Punto::Punto(float i, float j)
{
    x=i;
    y=j;
}
        Punto Punto::operator*(float n1)
        {
            Punto temp;
            temp.x = n1 * x;
            temp.y = n1 * y;
            return temp;
        }
        Punto Punto::operator/(float n1)
        {
            Punto temp;
            if(n1 != 0)
            {
                temp.x = x / n1;
                temp.y = y / n1;
            }
            return 0;
        }

        Punto Punto::operator+(Punto p1)
        {
            Punto temp;
            temp.x = x + p1.x;
            temp.y = y + p1.y;
            return temp;
        }

        void Punto::operator=(Punto p1)
        {
            x = p1.x;
            y = p1.y;
        }

        Punto Punto::operator-(Punto p1)
        {
            Punto temp;
            temp.x = x - p1.x;
            temp.y = y - p1.y;
            return temp;
        }
        void Punto::print()
        {
            cout << "(" << x << "," << y << ")" << endl;
        }

// class destructor
Punto::~Punto()
{
	// insert your code here
}
