// Class automatically generated by Dev-C++ New Class wizard

#ifndef PUNTO_H
#define PUNTO_H

// No description
class Punto
{
	protected:
        float x,y;     
                
    public:
		// class constructor
		Punto();
		Punto(float);
		Punto(float, float);
        void set(float i, float j){ x=i; y=j; }
        void operator=(Punto);
        Punto operator+(Punto);
        Punto operator-(Punto);
        Punto operator*(float);
        Punto operator/(float);
        void print();               

		// class destructor
		~Punto();
};

#endif // PUNTO_H
