// Class automatically generated by Dev-C++ New Class wizard

#include "punto3d.h" // class's header file

// class constructor
Punto3D::Punto3D()
{
	x = 0;
	y = 0;
    z = 0;
}
Punto3D::Punto3D(float i)
{
	x = i;
	y = x;
	z = y;
}
Punto3D::Punto3D(float i, float j, float k)
{
	x = i;
	y = j;
    z = k;
}

// class destructor
Punto3D::~Punto3D()
{
	// insert your code here
}
