// Class automatically generated by Dev-C++ New Class wizard

#include "vector.h" // class's header file

// class constructor
Vector::Vector()
{
	// insert your code here
}

// class destructor
Vector::~Vector()
{
	// insert your code here
}
