// Class automatically generated by Dev-C++ New Class wizard

#ifndef VECTOR3D_H
#define VECTOR3D_H

#include "vector.h" // inheriting class's header file

// No description
class Vector3D : public Vector
{
	public:
		// class constructor
		Vector3D();
		// class destructor
		~Vector3D();
};

#endif // VECTOR3D_H
