// Class automatically generated by Dev-C++ New Class wizard

#include "vector3d.h" // class's header file

// class constructor
Vector3D::Vector3D()
{
	// insert your code here
}

// class destructor
Vector3D::~Vector3D()
{
	// insert your code here
}
