// Class automatically generated by Dev-C++ New Class wizard

#ifndef VECTOR_H
#define VECTOR_H

// No description
class Vector
{
	public:
		// class constructor
		Vector();
		// class destructor
		~Vector();
};

#endif // VECTOR_H
